### ISSUE TITLE
inappwebview does not show connect to mobile wallet on ios ?

### ISSUE THREAD

**Issue by lxl518000** [Orange-Wallet/wallet-connect-dart#14]
inappwebview does not show connect to mobile wallet on ios ,

but a list of some wallet app .

how can i use it on ios?

thanks!

**Comment by Abhimanyu121** [comment]
Hey you will need to register your wallet on wallet connect registry and then use wallet URI to connect, @thelazyindian can you guide him better

**Comment by juliengss** [comment]
Hey,
I don't really understand your answer can you be more explicit "you will need to register your wallet on wallet connect registry and then use wallet URI to connect"
- How can i register my wallet on wallet connect ?
- How can I get the wallet URI ?

**Comment by rennylangat** [comment]
I had a similar question as @juliengss . Is there like some sort of universal database that holds all wallets and one has to register there so that their wallet comes in as an option when one presses connect on any dApp site?

**Comment by Abhimanyu121** [comment]
Hey @rennylangat  yes, check this out https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33

**Comment by lxl518000** [comment]
thanks for all guys.
i have got how to use it on ios.

**Comment by mopilo** [comment]
@lxl518000 how did you do it?
