### ISSUE TITLE
Update Session never updates.

### ISSUE THREAD

**Issue by erginersoy** [Orange-Wallet/wallet-connect-dart#16]
`Future<void> updateSession({
    List<String>? accounts,
    int? chainId,
    bool approved = true,
  }) async {
    final param = WCSessionUpdate(
      approved: approved,
      chainId: _chainId ?? chainId,
      accounts: accounts,
    );
    final request = JsonRpcRequest(
      id: DateTime.now().millisecondsSinceEpoch,
      method: WCMethod.SESSION_UPDATE,
      params: [param.toJson()],
    );
    return _encryptAndSend(jsonEncode(request.toJson()));
  }`

In this block chainId is never updated. It always uses current `_chainId `.

to Update Session we need to call `approveSession` method first then call `updateSession` method

**Comment by Abhimanyu121** [comment]
Thanks a lot for pointing it out and raising the PR.
