### ISSUE TITLE
Sign message error

### ISSUE THREAD

**Issue by Fury76** [Orange-Wallet/wallet-connect-dart#2]
step1: 
open the opensea.io, and connect walletconnect

step2:
open  profile -> collected, and open the own collect.

step3:
click the sell button, to sell my collect.

step4:
set the price, click "Complete listing" button, then click "unlock" button 

step5: 
click "sign" button in walletconnect.

then error:
There was an error with your transaction. Please try again.

<img width="1781" alt="WX20211005-115439@2x" src="https://user-images.githubusercontent.com/7465355/135957586-35111edf-0d84-47f5-97eb-acb2d2aade2a.png">

**Comment by thelazyindian** [comment]
Check with https://github.com/Orange-Wallet/wallet-connect-dart/commit/aa1b2408f9c5789407b86039ccbff1c19dd07f9c

**Comment by thelazyindian** [comment]
Fixed with https://github.com/wakumo/eth-sig-util/commit/0fd33b2e91b223ed547cae26779fb1fa7b32e8ce So eth_sig_util: ^0.0.6 onwards you won't have this issue.
