### ISSUE TITLE
Unhandled Exception: Invalid argument(s): `algo_signTxn`

### ISSUE THREAD

**Issue by froze9063** [Orange-Wallet/wallet-connect-dart#31]
Hello guys, I got this error when doing transaction from dApps for algorand
<img width="1347" alt="Screen Shot 2022-08-09 at 18 21 15" src="https://user-images.githubusercontent.com/26326325/183635423-8c059f86-a857-415a-9551-3bf10362b28a.png">
d

**Comment by thelazyindian** [comment]
Reolved https://github.com/Orange-Wallet/wallet-connect-dart/pull/42.
