### ISSUE TITLE
Android Support/Docs 

### ISSUE THREAD

**Issue by Sameerkash** [Orange-Wallet/wallet-connect-dart#7]
I've been trying the example and connecting to Metamask app on my phone, I am unsure if this is web-only, or does it support android too, because it doesn't show a list of apps when I open it on my android phone, do I need to make some additional configurations ? I was unsure as there is not any documentation around it, within the codebase too. It'd be great if I can get some help figuring this out.

**Comment by wmyao** [comment]
Hi, we meet same issue for android phone. It does not show a list of wallet app. Have you resolved this issue? Thanks.

**Comment by juanagu** [comment]
Hello @Sameerkash, how do you solve it? I know that the UX is diff on Android and is not showing the list of wallet apps. 

https://docs.walletconnect.com/mobile-linking

But I couldn't find information about how to setup the deep link on Android.

https://stackoverflow.com/questions/66451913/android-deep-link-wc-scheme
